name: aescrypto
description: Encrypt & Decrypt plain text and files with AES algorithm.
version: 2.3.0
homepage: https://github.com/MahmoudKhalid
repository: https://github.com/MahmoudKhalid/aescrypto-dart
issue_tracker: https://github.com/MahmoudKhalid/aescrypto-dart/issues
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  convert: ^3.1.1
  crypto: ^3.0.2
  path: ^1.8.3
  collection: ^1.17.0
  encrypt:
    git:
      url: https://github.com/MahmoudKhalid/encrypt.git
      ref: 5.x

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
